version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme%
    ports:
      - "9200:9200"

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.0
    user: root
    volumes:
      - /home/hii/filebeat1.yml:/usr/share/filebeat/filebeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx/logs:/var/log/nginx
    command: ["--strict.perms=false"]

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
